paths:
  source_data_path: "notebooks/data/Training_Data.csv"  # Source data path for ingestion

data_ingestion:
  raw_data_path: "artifacts/data_ingestion/raw.csv"
  train_data_path: "artifacts/data_ingestion/train.csv"
  test_data_path: "artifacts/data_ingestion/test.csv"

data_validation:
  schema_file_path: "artifacts/data_validation/schema.json"

data_preprocessing:
  preprocessed_train_data_path: "artifacts/data_preprocessing/preprocessed_train.csv"
  preprocessed_test_data_path: "artifacts/data_preprocessing/preprocessed_test.csv"


data_transformation:
  preprocessor_ob_file_path: "artifacts/data_transformation/preprocessor.pkl"
  preprocessor_label_ob_file: "artifacts/data_transformation/label_encoder.pkl"
  train_array_file_path: 'artifacts/data_transformation/train_array.npy'
  test_array_file_path: 'artifacts/data_transformation/test_array.npy'

model_trainer:
  trained_model_file_path: "artifacts/model_training/model.pkl"
  param_file_path: "config/params.yaml"
  schema_file_path: "config/schema.yaml"

model_evaluation:
  evaluation_file_path: "artifacts/model_evaluation/evaluation.json"
  
logging:
  log_file: "logs/data_ingestion.log"
  log_level: "INFO"
